### ISSUE TITLE
Issue while installing django-scooby-profiler for  Python2.7

### ISSUE THREAD

**Issue by Skchoudhary** [shhaumb/django-scooby-profiler#3]
Error while doing pip install, due to wrong keyword argument
Python version: 2.7
OS: Ubuntu 16LTS

In Python2.7 **open function argument list**
open(name[, mode[, buffering]]) -> file object

In Python3 **open function argument list**
open(file, mode='r', buffering=-1, encoding=None, errors=None, newline=None, closefd=True, opener=None)

Traceback:
```
Collecting django-scooby-profiler
  Using cached https://files.pythonhosted.org/packages/f0/34/8e79f3b8e09d30e927a6c69b20069ac521e888a3f59793111122ff68d006/django-scooby-profiler-2.0.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-G2Bf4B/django-scooby-profiler/setup.py", line 6, in <module>
        with open(path.join(this_directory, 'README.md'), encoding='utf-8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-G2Bf4B/django-scooby-profiler/
```

using io.open can be one solution, but have to see what will be best way.
https://stackoverflow.com/questions/10971033/backporting-python-3-openencoding-utf-8-to-python-2

**Comment by shhaumb** [comment]
Oh, setup.py is failing for Python2. I will fix this and will let you know. Thanks!

**Comment by shhaumb** [comment]
@Skchoudhary I have fixed the issue. Can you please check by installing new version?

**Comment by Skchoudhary** [comment]
@shhaumb sure

**Comment by Skchoudhary** [comment]
@shhaumb Working fine now :+1:
